### ISSUE TITLE
Extra attributes in the data model - approach

### ISSUE THREAD

**Issue by johankumps** [smart-data-models/dataModel.Transportation#12]
Hello,

We are using computer vision to determine the number of vehicles passing by a certain point in the city as well as their speed.  We should also have a place to store the number of vehicles that were speeding in a certain RoadSegment.

Looking at the TrafficFlowObserved model I can store the average speed. How about the counter per vehicle type? Should I extend the model with extra attributes or am I missing something?

In case we have to add our own attributes, is their a process that allows for the extention of the specification?

Thanks for your reply.

Kind regards,
Johan,

**Comment by albertoabellagarcia** [comment]
Basically, the answer to all your questions is yes.
1) Could you extend the model for your own purposes about counting vehicles?. 
Definitely, because the license of the data models says so. 
2) Could you suggest an extension of the model for allocating such attributes?. 
Definitely. As long as you 
- Have a use case 
- Have a strict definition of the attributes ([check the attribute database](https://smartdatamodels.org/index.php/ddbb-of-properties-descriptions/) for something similar. Reusing is encouraged) 
- The attributes are generic enough (and makes sense in the use of the data model)
- Sometimes are regulations that already define such attributes. Review DATEX 2.3 just in case.
The process how to modify or create a data model is in the [contribution manual](https://bit.ly/contribution_manual). Check it out before doing a PR on the model. 

thanks a lot
